### ISSUE TITLE
Instant crash at launch

### ISSUE THREAD

**Issue by SteveNguyen** [moveit/mujoco_ros2_control#22]
All the examples crashe immediately with no log or specific error message.
Example for `ros2 launch mujoco_ros2_control_demos cart_example_position.launch.py`
![Image](https://github.com/user-attachments/assets/984282a7-4920-47cb-a71d-f6bdaa5df186)

Same behavior for both the main and humble-devel branches.
Digging a little bit it seems like calls to controller_manager (read/write and update) in the update() method of MujocoRos2Control provoke the problem? https://github.com/moveit/mujoco_ros2_control/blob/ba232c01d3ec658a761318950d6a1290760aa9bb/mujoco_ros2_control/src/mujoco_ros2_control.cpp#L144
Any idea?

Tested under:
- Ubuntu 22.04.3
- ROS2 Humble

**Comment by sangteak601** [comment]
It works fine on my machine. It looks like a dependency issue.

Can you try installing dependencies before launching them?
```
rosdep update && rosdep install --from-paths ./ --ignore-src -y
```

**Comment by SteveNguyen** [comment]
Well, oddly enough, it works if I compile everything in debug mode with:
`colcon build --packages-select mujoco_ros2_control --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Debug`

**Comment by eholum** [comment]
Did some quick debugging here with the workflow in https://github.com/moveit/mujoco_ros2_control/pull/26, definitely a weird bug somewhere.

On my machines the segfault is coming from the write loop in: https://github.com/moveit/mujoco_ros2_control/blob/main/mujoco_ros2_control/src/mujoco_system.cpp#L61. If I remove that then a similar segfault happens in `read`. In both cases it seems to be an issue with the iterator on `joint_states_` incorrectly going past the end of the vector

Here's the stack trace:

```
# Running the gripper mimic joint demo
[INFO] [1739028468.752553858] [mujoco_ros2_control_node]: Mujoco ros2 controller has been successfully initialized !
[INFO] [1739028468.752591688] [mujoco_ros2_control_node]: Mujoco rendering has been successfully initialized !
[New Thread 0xffffecc2df80 (LWP 2652)]

Thread 1 "mujoco_ros2_con" received signal SIGSEGV, Segmentation fault.
[New Thread 0xffffecc2df80 (LWP 2652)]

Thread 1 "mujoco_ros2_con" received signal SIGSEGV, Segmentation fault.
mujoco_ros2_control::MujocoSystem::write (this=0xaaaaaabb1890, time=..., period=...) at /home/dev/ws/src/mujoco_ros2_control/mujoco_ros2_control/src/mujoco_system.cpp:67
67              double error = joint_state.position_command - mj_data_->qpos[joint_state.mj_pos_adr];
(gdb) bt
#0  mujoco_ros2_control::MujocoSystem::write (this=0xaaaaaabb1890, time=..., period=...) at /home/dev/ws/src/mujoco_ros2_control/mujoco_ros2_control/src/mujoco_system.cpp:67
#1  0x0000fffff7dcd864 in hardware_interface::System::write(rclcpp::Time const&, rclcpp::Duration const&) () from /opt/ros/humble/lib/libhardware_interface.so
#2  0x0000fffff7db07b4 in hardware_interface::ResourceManager::write(rclcpp::Time const&, rclcpp::Duration const&) () from /opt/ros/humble/lib/libhardware_interface.so
#3  0x0000fffff7eb26d0 in controller_manager::ControllerManager::write(rclcpp::Time const&, rclcpp::Duration const&) () from /opt/ros/humble/lib/libcontroller_manager.so
#4  0x0000aaaaaaad38c0 in mujoco_ros2_control::MujocoRos2Control::update (this=this@entry=0xffffffffe5e0) at /usr/include/c++/11/bits/shared_ptr_base.h:1295
#5  0x0000aaaaaaad0220 in main (argc=<optimized out>, argv=<optimized out>) at /home/dev/ws/src/mujoco_ros2_control/mujoco_ros2_control/src/mujoco_ros2_control_node.cpp:54
(gdb) bt full
#0  mujoco_ros2_control::MujocoSystem::write (this=0xaaaaaabb1890, time=..., period=...) at /home/dev/ws/src/mujoco_ros2_control/mujoco_ros2_control/src/mujoco_system.cpp:67
        error = <optimized out>
        joint_state = @0xaaaaaabc0e40: {name = <error: Cannot access memory at address 0x616e00746e696f6a>, position = 0, velocity = 0, effort = 9.2711411334410387e-310, position_command = 2.2727019708697341e-322, 
          velocity_command = 2.2727019708697341e-322, effort_command = 2.2869000570019413e+243, min_position_command = 9.2711411359453587e-310, max_position_command = 2.2727019708697341e-322, 
          min_velocity_command = 2.2727019708697341e-322, max_velocity_command = 4.2701187058144046e+257, min_effort_command = 9.2711411340600042e-310, max_effort_command = 2.3221085354538588e-322, position_pid = {gains_buffer_ = {
              realtime_data_ = 0x2f, non_realtime_data_ = 0x6361667265746e69, new_data_available_ = 96, mutex_ = {<std::__mutex_base> = {_M_mutex = {__data = {__lock = 35, __count = 0, __owner = 35, __nusers = 0, __kind = 792357999, 
                      __spins = 1701670760, __list = {__prev = 0xaaaaaabccaf0, __next = 0x12}}, 
                    __size = "#\000\000\000\000\000\000\000#\000\000\000\000\000\000\000ol:/home\360ʼ\252\252\252\000\000\022\000\000\000\000\000\000\000\022\000\000\000\000\000\000", __align = 35}}, <No data fields>}}, 
            p_error_last_ = 3.7767302121001554e+209, p_error_ = 9.2711411317975788e-310, i_error_ = 3.2114266979681025e-322, d_error_ = 3.2114266979681025e-322, cmd_ = 8.3896246038661211e+242, error_dot_ = 9.2711411334702874e-310}, 
          velocity_pid = {gains_buffer_ = {realtime_data_ = 0x18, non_realtime_data_ = 0x18, new_data_available_ = 110, mutex_ = {<std::__mutex_base> = {_M_mutex = {__data = {__lock = -1430515872, __count = 43690, __owner = 10, 
                      __nusers = 0, __kind = 1163021909, __spins = 1447841619, __list = {__prev = 0x4445, __next = 0xaaaaaabbb860}}, 
                    __size = "`\017\274\252\252\252\000\000\n\000\000\000\000\000\000\000UNRESOLVED\000\000\000\000\000\000`\270\273\252\252\252\000\000c\000\000\000\000\000\000", __align = 187649985613664}}, <No data fields>}}, 
            p_error_last_ = 4.8912498938283408e-322, p_error_ = 3.6314392165019276e+257, i_error_ = 1.6716262987928307e-260, d_error_ = 3.2114266979681025e-322, cmd_ = 8.3843909568263659e+242, error_dot_ = 6.9730255384564957e+252}, 
          is_position_control_enabled = 114, is_velocity_control_enabled = 111, is_effort_control_enabled = 108, is_pid_enabled = 58, joint_limits = {min_position = 5.3038770948208529e+180, max_position = 1.5779139171305899e+161, 
            max_velocity = 7.4786705568602259e+247, max_acceleration = 1.3543401650698773e-306, max_jerk = 3.2114266979681025e-322, max_effort = 9.2859870686790636e+242, has_position_limits = 100, has_velocity_limits = 119, 
            has_acceleration_limits = 97, has_jerk_limits = 114, has_effort_limits = 101, angle_wraparound = 95}, is_mimic = 109, mimicked_joint_index = 1937010277, mimic_multiplier = 2.6942923793319522e+276, mj_joint_type = 1835365491, 
          mj_pos_adr = 1835888451, mj_vel_adr = 1298427489}
        __for_range = <optimized out>
        __for_begin = <optimized out>
        __for_end = <optimized out>
#1  0x0000fffff7dcd864 in hardware_interface::System::write(rclcpp::Time const&, rclcpp::Duration const&) () from /opt/ros/humble/lib/libhardware_interface.so
No symbol table info available.
#2  0x0000fffff7db07b4 in hardware_interface::ResourceManager::write(rclcpp::Time const&, rclcpp::Duration const&) () from /opt/ros/humble/lib/libhardware_interface.so
No symbol table info available.
#3  0x0000fffff7eb26d0 in controller_manager::ControllerManager::write(rclcpp::Time const&, rclcpp::Duration const&) () from /opt/ros/humble/lib/libcontroller_manager.so
No symbol table info available.
#4  0x0000aaaaaaad38c0 in mujoco_ros2_control::MujocoRos2Control::update (this=this@entry=0xffffffffe5e0) at /usr/include/c++/11/bits/shared_ptr_base.h:1295
        sim_time = 2.2727019708697341e-322
        sim_time_sec = <optimized out>
        sim_time_nanosec = <optimized out>
        sim_time_ros = <incomplete type>
        sim_period = {_vptr.Duration = 0xfffff7c66d40, rcl_duration_ = {nanoseconds = 0}}
#5  0x0000aaaaaaad0220 in main (argc=<optimized out>, argv=<optimized out>) at /home/dev/ws/src/mujoco_ros2_control/mujoco_ros2_control/src/mujoco_ros2_control_node.cpp:54
        simstart = 0
        node = std::shared_ptr<rclcpp::Node> (use count 3, weak count 1) = {get() = 0xaaaaaab500b0}
        __func__ = <optimized out>
        model_path = "/home/dev/ws/install/mujoco_ros2_control_demos/share/mujoco_ros2_control_demos/mujoco_models/test_gripper_mimic_joint.xml"
        error = "\000ould not load binary model", '\000' <repeats 972 times>
        control = {node_ = std::shared_ptr<rclcpp::Node> (use count 3, weak count 1) = {get() = 0xaaaaaab500b0}, mj_model_ = 0xaaaaaabc1900, mj_data_ = 0xaaaaaac06c80, logger_ = {
            name_ = std::shared_ptr<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> (use count 1, weak count 0) = {get() = 0xaaaaaabb3430}}, 
          robot_hw_sim_loader_ = std::shared_ptr<pluginlib::ClassLoader<mujoco_ros2_control::MujocoSystemInterface>> (use count 1, weak count 0) = {get() = 0xaaaaaabd0890}, 
          controller_manager_ = std::shared_ptr<controller_manager::ControllerManager> (use count 1, weak count 1) = {get() = 0xaaaaaabd5aa0}, 
          cm_executor_ = std::shared_ptr<rclcpp::executors::MultiThreadedExecutor> (use count 2, weak count 0) = {get() = 0xaaaaaabcc2c0}, cm_thread_ = {_M_id = {_M_thread = 281474662391680}}, stop_cm_thread_ = false, control_period_ = {
            _vptr.Duration = 0xfffff7c66d40, rcl_duration_ = {nanoseconds = 10000000}}, last_update_sim_time_ros_ = <incomplete type>, 
          clock_publisher_ = std::shared_ptr<rclcpp::Publisher<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >> (use count 1, weak count 1) = {get() = 0xaaaaaabb0990}}
        rendering = <optimized out>
```

Note that it's referencing `joint_state = @0xaaaaaabc0e40`, which checking the `joint_states_` vector is the "3rd" entry:

```
(gdb) print &joint_states_[0]
$2 = (mujoco_ros2_control::MujocoSystem::JointState *) 0xaaaaaabc0aa0
(gdb) print &joint_states_[1]
$3 = (mujoco_ros2_control::MujocoSystem::JointState *) 0xaaaaaabc0c70
(gdb) print &joint_states_[2]
$4 = (mujoco_ros2_control::MujocoSystem::JointState *) 0xaaaaaabc0e40
```

And the value at that pointer is obviously garbled, so the program  faults:

```
(gdb) print joint_states_[2]
$5 = {name = <error: Cannot access memory at address 0x616e00746e696f6a>, position = 0, velocity = 0, effort = 9.2711411334410387e-310, position_command = 2.2727019708697341e-322, velocity_command = 2.2727019708697341e-322, 
  effort_command = 2.2869000570019413e+243, min_position_command = 9.2711411359453587e-310, max_position_command = 2.2727019708697341e-322, min_velocity_command = 2.2727019708697341e-322, max_velocity_command = 4.2701187058144046e+257, 
  min_effort_command = 9.2711411340600042e-310, max_effort_command = 2.3221085354538588e-322, position_pid = {gains_buffer_ = {realtime_data_ = 0x2f, non_realtime_data_ = 0x6361667265746e69, new_data_available_ = 96, 
      mutex_ = {<std::__mutex_base> = {_M_mutex = {__data = {__lock = 35, __count = 0, __owner = 35, __nusers = 0, __kind = 792357999, __spins = 1701670760, __list = {__prev = 0xaaaaaabccaf0, __next = 0x12}}, 
            __size = "#\000\000\000\000\000\000\000#\000\000\000\000\000\000\000ol:/home\360ʼ\252\252\252\000\000\022\000\000\000\000\000\000\000\022\000\000\000\000\000\000", __align = 35}}, <No data fields>}}, 
    p_error_last_ = 3.7767302121001554e+209, p_error_ = 9.2711411317975788e-310, i_error_ = 3.2114266979681025e-322, d_error_ = 3.2114266979681025e-322, cmd_ = 8.3896246038661211e+242, error_dot_ = 9.2711411334702874e-310}, 
  velocity_pid = {gains_buffer_ = {realtime_data_ = 0x18, non_realtime_data_ = 0x18, new_data_available_ = 110, mutex_ = {<std::__mutex_base> = {_M_mutex = {__data = {__lock = -1430515872, __count = 43690, __owner = 10, __nusers = 0, 
              __kind = 1163021909, __spins = 1447841619, __list = {__prev = 0x4445, __next = 0xaaaaaabbb860}}, 
            __size = "`\017\274\252\252\252\000\000\n\000\000\000\000\000\000\000UNRESOLVED\000\000\000\000\000\000`\270\273\252\252\252\000\000c\000\000\000\000\000\000", __align = 187649985613664}}, <No data fields>}}, 
    p_error_last_ = 4.8912498938283408e-322, p_error_ = 3.6314392165019276e+257, i_error_ = 1.6716262987928307e-260, d_error_ = 3.2114266979681025e-322, cmd_ = 8.3843909568263659e+242, error_dot_ = 6.9730255384564957e+252}, 
  is_position_control_enabled = 114, is_velocity_control_enabled = 111, is_effort_control_enabled = 108, is_pid_enabled = 58, joint_limits = {min_position = 5.3038770948208529e+180, max_position = 1.5779139171305899e+161, 
    max_velocity = 7.4786705568602259e+247, max_acceleration = 1.3543401650698773e-306, max_jerk = 3.2114266979681025e-322, max_effort = 9.2859870686790636e+242, has_position_limits = 100, has_velocity_limits = 119, 
    has_acceleration_limits = 97, has_jerk_limits = 114, has_effort_limits = 101, angle_wraparound = 95}, is_mimic = 109, mimicked_joint_index = 1937010277, mimic_multiplier = 2.6942923793319522e+276, mj_joint_type = 1835365491, 
  mj_pos_adr = 1835888451, mj_vel_adr = 1298427489}
```

But confirmed that we have the correct size of the vector:

```
(gdb) print joint_states_.size()
$1 = 2
```

My only guess is that something is corrupting the memory around that iterator at run time, but as of now I have no idea what it might be.

**Comment by eholum** [comment]
Potentially resolved in #27. @SteveNguyen if you get a chance to check it out can you let me know?
